-- GENERATED by scripts/generate-seed-sql.ts from src/data/apex.ts — do not edit by hand.
-- Run after supabase/schema.sql. Re-running is safe: catalogue rows upsert and the
-- demo bookings are rebuilt via apex_reset_demo() (which only touches is_demo rows).

begin;

insert into ops_settings (id, setup_minutes, inspection_minutes, turnaround_minutes, dispatch_start, dispatch_end,
  min_lead_minutes, deposit_rate, price_rounding, travel_rounding, free_change_hours, peak_windows)
values (true, 20, 15, 10, 420, 1170,
  120, 0.3, 500, 5, 12,
  array[int4range(420, 600), int4range(960, 1170)])
on conflict (id) do update set setup_minutes = excluded.setup_minutes, inspection_minutes = excluded.inspection_minutes,
  turnaround_minutes = excluded.turnaround_minutes, dispatch_start = excluded.dispatch_start, dispatch_end = excluded.dispatch_end,
  min_lead_minutes = excluded.min_lead_minutes, deposit_rate = excluded.deposit_rate, price_rounding = excluded.price_rounding,
  travel_rounding = excluded.travel_rounding, free_change_hours = excluded.free_change_hours, peak_windows = excluded.peak_windows;

insert into demo_settings (id, day_offset_from, day_offset_to) values (true, -1, 13)
on conflict (id) do update set day_offset_from = excluded.day_offset_from, day_offset_to = excluded.day_offset_to;

insert into vehicle_classes (id, label, base_minutes, price_multiplier) values
  ('sedan', 'Sedan', 90, 1),
  ('coupe', 'Coupe', 100, 1.1),
  ('suv', 'SUV', 120, 1.25),
  ('pickup', 'Pickup', 135, 1.3),
  ('luxury', 'Luxury', 150, 1.5)
on conflict (id) do update set label = excluded.label, base_minutes = excluded.base_minutes, price_multiplier = excluded.price_multiplier;

insert into services (slug, name, description, base_price, base_duration_minutes, active) values
  ('signature-reset', 'Signature Reset', 'Snow-foam pre-wash, two-bucket contact wash, interior vacuum and wipe-down, wheel faces, streak-free glass.', 45000, 0, true),
  ('interior-recovery', 'Interior Recovery', 'Steam extraction of seats and carpets, leather clean and condition, vents, trims and headliner spot-treat.', 65000, 45, true),
  ('exterior-correction', 'Exterior Correction', 'Iron and tar decontamination, clay bar, single-stage machine polish to lift swirls and restore depth.', 110000, 90, true),
  ('ceramic-shield', 'Ceramic Shield', 'Full paint prep, panel wipe and a 24-month ceramic coating. Wheel faces and glass coated too.', 240000, 150, true)
on conflict (slug) do update set name = excluded.name, description = excluded.description, base_price = excluded.base_price,
  base_duration_minutes = excluded.base_duration_minutes, active = true;

insert into service_addons (slug, name, price_delta, duration_delta_minutes, active) values
  ('engine-bay', 'Engine Bay Detail', 15000, 25, true),
  ('pet-hair', 'Pet-Hair Recovery', 12000, 30, true),
  ('headlight-restoration', 'Headlight Restoration', 18000, 35, true),
  ('odor-treatment', 'Odour Treatment', 10000, 20, true),
  ('wheel-deep', 'Wheel & Caliper Deep Clean', 14000, 25, true)
on conflict (slug) do update set name = excluded.name, price_delta = excluded.price_delta,
  duration_delta_minutes = excluded.duration_delta_minutes, active = true;

insert into service_zones (id, name, travel_minutes, peak_factor, surcharge, serviced) values
  ('ikate', 'Ikate / Elegushi', 10, 1.2, 0, true),
  ('lekki-phase-1', 'Lekki Phase 1', 15, 1.3, 0, true),
  ('osapa', 'Osapa London', 15, 1.3, 0, true),
  ('chevron', 'Chevron / Conservation', 20, 1.4, 0, true),
  ('victoria-island', 'Victoria Island', 30, 1.5, 5000, true),
  ('ikoyi', 'Ikoyi', 30, 1.5, 5000, true),
  ('ajah', 'Ajah', 35, 1.5, 7500, true),
  ('sangotedo', 'Sangotedo', 45, 1.4, 10000, true),
  ('yaba', 'Yaba / Surulere', 75, 1.6, 0, false),
  ('ikeja', 'Ikeja / GRA', 95, 1.6, 0, false)
on conflict (id) do update set name = excluded.name, travel_minutes = excluded.travel_minutes, peak_factor = excluded.peak_factor,
  surcharge = excluded.surcharge, serviced = excluded.serviced;

insert into mobile_units (id, name, crew, status, home_zone, active) values
  ('unit-01', 'Mobile Unit 01', 'Tunde · Kelechi', 'active', 'ikate', true),
  ('unit-02', 'Mobile Unit 02', 'Sade · Ibrahim', 'active', 'ikate', true),
  ('unit-03', 'Mobile Unit 03', 'Chidi · Mariam', 'active', 'ikate', true)
on conflict (id) do update set name = excluded.name, crew = excluded.crew, home_zone = excluded.home_zone, active = true;

delete from demo_seed_templates;
insert into demo_seed_templates (weekday, unit_id, start_time, vehicle_class, vehicle_label, service_slug, addon_slugs, zone_id, customer_name, pending_deposit) values
  (0, 'unit-01', '09:00', 'luxury', 'Lexus LX 600', 'signature-reset', '{}'::text[], 'ikoyi', 'Adaeze O.', false),
  (0, 'unit-01', '14:30', 'suv', 'Toyota Prado', 'interior-recovery', array['odor-treatment'], 'lekki-phase-1', 'Tobi A.', false),
  (0, 'unit-02', '08:00', 'sedan', 'Mercedes C300', 'signature-reset', '{}'::text[], 'osapa', 'Femi K.', false),
  (0, 'unit-02', '11:30', 'suv', 'BMW X5', 'exterior-correction', '{}'::text[], 'chevron', 'Zainab B.', false),
  (0, 'unit-03', '10:00', 'pickup', 'Toyota Hilux', 'signature-reset', array['engine-bay'], 'ajah', 'Chuka E.', false),
  (1, 'unit-01', '10:30', 'suv', 'Lexus RX 350', 'signature-reset', '{}'::text[], 'lekki-phase-1', 'Ifeoma N.', false),
  (1, 'unit-02', '11:00', 'luxury', 'Range Rover Sport', 'exterior-correction', '{}'::text[], 'victoria-island', 'Seyi D.', false),
  (1, 'unit-03', '14:00', 'sedan', 'Honda Accord', 'interior-recovery', array['pet-hair'], 'ikate', 'Bola A.', false),
  (2, 'unit-01', '11:00', 'coupe', 'BMW M4', 'exterior-correction', '{}'::text[], 'ikoyi', 'Kemi F.', false),
  (2, 'unit-02', '10:30', 'suv', 'Toyota Highlander', 'signature-reset', '{}'::text[], 'osapa', 'Emeka U.', false),
  (2, 'unit-03', '13:30', 'sedan', 'Toyota Camry', 'signature-reset', array['headlight-restoration'], 'chevron', 'Nneka I.', false),
  (3, 'unit-01', '10:30', 'luxury', 'Mercedes-Benz G 63', 'ceramic-shield', '{}'::text[], 'victoria-island', 'Dapo L.', false),
  (3, 'unit-02', '11:00', 'sedan', 'Lexus ES 350', 'interior-recovery', '{}'::text[], 'lekki-phase-1', 'Halima S.', false),
  (3, 'unit-03', '14:30', 'pickup', 'Ford Ranger', 'signature-reset', '{}'::text[], 'sangotedo', 'Ayo M.', false),
  (4, 'unit-01', '10:30', 'suv', 'Porsche Cayenne', 'exterior-correction', '{}'::text[], 'ikoyi', 'Tolu B.', false),
  (4, 'unit-02', '12:00', 'sedan', 'Toyota Corolla', 'signature-reset', '{}'::text[], 'ikate', 'Ugo C.', false),
  (4, 'unit-03', '10:30', 'suv', 'Kia Sorento', 'interior-recovery', array['pet-hair', 'odor-treatment'], 'ajah', 'Funmi R.', false),
  (5, 'unit-01', '08:00', 'suv', 'Lexus GX 460', 'signature-reset', '{}'::text[], 'lekki-phase-1', 'Amaka P.', false),
  (5, 'unit-01', '13:30', 'luxury', 'Range Rover Vogue', 'exterior-correction', '{}'::text[], 'ikoyi', 'Obinna J.', false),
  (5, 'unit-02', '10:30', 'pickup', 'Toyota Hilux', 'signature-reset', '{}'::text[], 'chevron', 'Musa G.', false),
  (5, 'unit-02', '16:30', 'sedan', 'Mercedes E350', 'signature-reset', '{}'::text[], 'lekki-phase-1', 'Yemi T.', false),
  (5, 'unit-03', '14:00', 'coupe', 'Mercedes-AMG C63', 'ceramic-shield', '{}'::text[], 'osapa', 'Kunle W.', true),
  (6, 'unit-01', '08:00', 'suv', 'BMW X6', 'signature-reset', '{}'::text[], 'lekki-phase-1', 'Ronke H.', false),
  (6, 'unit-01', '11:30', 'luxury', 'Lexus LX 570', 'exterior-correction', '{}'::text[], 'ikoyi', 'Victor N.', false),
  (6, 'unit-02', '08:30', 'sedan', 'Toyota Camry', 'interior-recovery', array['pet-hair'], 'ikate', 'Esther O.', false),
  (6, 'unit-02', '13:00', 'suv', 'Mercedes GLE', 'signature-reset', array['engine-bay'], 'victoria-island', 'Gbenga A.', false),
  (6, 'unit-02', '17:00', 'sedan', 'Honda Civic', 'signature-reset', '{}'::text[], 'osapa', 'Daniel E.', false),
  (6, 'unit-03', '13:00', 'luxury', 'Range Rover Sport', 'ceramic-shield', '{}'::text[], 'chevron', 'Lola K.', false);

select apex_reset_demo();

commit;
