/**
 * Writes supabase/seed.sql from src/data/apex.ts so the database catalogue,
 * operating rules and demo week always match what the UI quotes.
 *
 *   npm run db:seed-sql
 */
import { writeFileSync } from 'node:fs';
import { ADDONS, OPS, SEED_DAY_OFFSETS, SEED_WEEK, SERVICES, UNITS, VEHICLE_CLASSES, ZONES } from '../src/data/apex.ts';

const q = (v: string | null | undefined) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(', ')}]` : `'{}'::text[]`);

const out: string[] = [];
out.push(`-- GENERATED by scripts/generate-seed-sql.ts from src/data/apex.ts — do not edit by hand.
-- Run after supabase/schema.sql. Re-running is safe: catalogue rows upsert and the
-- demo bookings are rebuilt via apex_reset_demo() (which only touches is_demo rows).

begin;
`);

out.push(`insert into ops_settings (id, setup_minutes, inspection_minutes, turnaround_minutes, dispatch_start, dispatch_end,
  min_lead_minutes, deposit_rate, price_rounding, travel_rounding, free_change_hours, peak_windows)
values (true, ${OPS.setupMinutes}, ${OPS.inspectionMinutes}, ${OPS.turnaroundMinutes}, ${OPS.dispatchStart}, ${OPS.dispatchEnd},
  ${OPS.minLeadMinutes}, ${OPS.depositRate}, ${OPS.priceRounding}, ${OPS.travelRounding}, ${OPS.freeChangeHours},
  array[${OPS.peakWindows.map(([a, b]) => `int4range(${a}, ${b})`).join(', ')}])
on conflict (id) do update set setup_minutes = excluded.setup_minutes, inspection_minutes = excluded.inspection_minutes,
  turnaround_minutes = excluded.turnaround_minutes, dispatch_start = excluded.dispatch_start, dispatch_end = excluded.dispatch_end,
  min_lead_minutes = excluded.min_lead_minutes, deposit_rate = excluded.deposit_rate, price_rounding = excluded.price_rounding,
  travel_rounding = excluded.travel_rounding, free_change_hours = excluded.free_change_hours, peak_windows = excluded.peak_windows;
`);

out.push(`insert into demo_settings (id, day_offset_from, day_offset_to) values (true, ${SEED_DAY_OFFSETS.from}, ${SEED_DAY_OFFSETS.to})
on conflict (id) do update set day_offset_from = excluded.day_offset_from, day_offset_to = excluded.day_offset_to;
`);

out.push(`insert into vehicle_classes (id, label, base_minutes, price_multiplier) values
${VEHICLE_CLASSES.map((v) => `  (${q(v.id)}, ${q(v.label)}, ${v.baseMinutes}, ${v.priceMultiplier})`).join(',\n')}
on conflict (id) do update set label = excluded.label, base_minutes = excluded.base_minutes, price_multiplier = excluded.price_multiplier;
`);

out.push(`insert into services (slug, name, description, base_price, base_duration_minutes, active) values
${SERVICES.map((s) => `  (${q(s.id)}, ${q(s.name)}, ${q(s.description)}, ${s.basePrice}, ${s.extraMinutes}, true)`).join(',\n')}
on conflict (slug) do update set name = excluded.name, description = excluded.description, base_price = excluded.base_price,
  base_duration_minutes = excluded.base_duration_minutes, active = true;
`);

out.push(`insert into service_addons (slug, name, price_delta, duration_delta_minutes, active) values
${ADDONS.map((a) => `  (${q(a.id)}, ${q(a.name)}, ${a.price}, ${a.minutes}, true)`).join(',\n')}
on conflict (slug) do update set name = excluded.name, price_delta = excluded.price_delta,
  duration_delta_minutes = excluded.duration_delta_minutes, active = true;
`);

out.push(`insert into service_zones (id, name, travel_minutes, peak_factor, surcharge, serviced) values
${ZONES.map((z) => `  (${q(z.id)}, ${q(z.name)}, ${z.travelMinutes}, ${z.peakFactor}, ${z.surcharge}, ${z.serviced})`).join(',\n')}
on conflict (id) do update set name = excluded.name, travel_minutes = excluded.travel_minutes, peak_factor = excluded.peak_factor,
  surcharge = excluded.surcharge, serviced = excluded.serviced;
`);

out.push(`insert into mobile_units (id, name, crew, status, home_zone, active) values
${UNITS.map((u) => `  (${q(u.id)}, ${q(u.name)}, ${q(u.crew)}, 'active', ${q(u.homeZone)}, true)`).join(',\n')}
on conflict (id) do update set name = excluded.name, crew = excluded.crew, home_zone = excluded.home_zone, active = true;
`);

const templates = Object.entries(SEED_WEEK).flatMap(([day, jobs]) =>
  jobs.map(
    (j) =>
      `  (${day}, ${q(UNITS[j.unit].id)}, '${j.start}', ${q(j.vehicle)}, ${q(j.label)}, ${q(j.service)}, ${arr(j.addons ?? [])}, ${q(j.zone)}, ${q(j.customer)}, ${!!j.pendingDeposit})`,
  ),
);
out.push(`delete from demo_seed_templates;
insert into demo_seed_templates (weekday, unit_id, start_time, vehicle_class, vehicle_label, service_slug, addon_slugs, zone_id, customer_name, pending_deposit) values
${templates.join(',\n')};
`);

out.push(`select apex_reset_demo();

commit;
`);

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n'));
console.log(`supabase/seed.sql written · ${templates.length} weekly demo jobs`);
